//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlyWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public System.Guid UserId { get; set; }
        public System.DateTime Birthday { get; set; }
        public short Weight { get; set; }
        public short Height { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<bool> Plan { get; set; }
    }
}
